FROM bitnami/spark:3.5.3

USER root

# Install system packages and Python dependencies
RUN install_packages curl

USER 1001

# Download Neo4j Spark connector
RUN curl https://repos.spark-packages.org/neo4j-contrib/neo4j-spark-connector/5.3.1-s_2.12/neo4j-spark-connector-5.3.1-s_2.12.jar \
    --output /opt/bitnami/spark/jars/neo4j-spark-connector-5.3.1-s_2.12.jar
