services:
  neo4j:
    image: neo4j:4.4-community
    volumes:
      - ./neo4j/logs:/logs
      - ./neo4j/config:/config
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=graph-data-science
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - scraper-network
      - spark-net
    profiles:
      - scraper
      - injection
      - streamlit
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  web-scraper:
    build:
      context: ./web-scraper
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - 8000:8000
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    networks:
      - scraper-network
    profiles:
      - scraper

  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./data:/home/jovyan/data:rw
      - ./functionalities:/home/jovyan/functionalities:rw
      - ./data-injection:/home/jovyan/data-injection:ro
      - ./:/home/jovyan/project:ro
    networks:
      - spark-net
    profiles:
      - injection
      - streamlit

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    depends_on:
      - spark
    deploy:
      replicas: 1
    volumes:
      - ./data:/home/jovyan/data:rw
      - ./functionalities:/home/jovyan/functionalities:rw
      - ./data-injection:/home/jovyan/data-injection:ro
      - ./:/home/jovyan/project:ro
    networks:
      - spark-net
    profiles:
      - injection
      - streamlit

  # Data injection service - now runs automatically during setup
  data-injection-setup:
    build:
      context: .
      dockerfile: Dockerfile.spark
    depends_on:
      neo4j:
        condition: service_healthy
      spark:
        condition: service_started
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - SPARK_MASTER_URL=spark://spark:7077
    volumes:
      - ./data:/home/jovyan/data:ro
      - ./functionalities:/home/jovyan/functionalities:ro
      - ./data-injection:/home/jovyan/data-injection:ro
      - ./:/home/jovyan/project:ro
    command: ["python", "/home/jovyan/project/run_injection.py"]
    networks:
      - spark-net
    profiles:
      - injection
      - streamlit
    restart: "no"  # Run once only

  # Keep the original data-injection service for manual runs
  data-injection:
    build:
      context: ./data-injection
    ports:
      - 8001:8000
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j:password@neo4j:7687
    volumes:
      # Mount your data directory
      - ./data:/app/data:ro
      - ./functionalities:/app/functionalities:ro
    networks:
      - spark-net
    profiles:
      - injection-manual

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      neo4j:
        condition: service_healthy
      spark:
        condition: service_started
    environment:
      - NEO4J_URI=bolt://neo4j:password@neo4j:7687
      - SPARK_MASTER_URL=spark://spark:7077
    volumes:
      - ./functionalities:/app/functionalities:ro
      - ./models:/app/models:ro
      - ./web-scraper:/app/scraper:ro
      - ./data:/app/data:ro
      - ./logs:/app/logs:rw
      - ./:/app/project:ro
    networks:
      - spark-net
    profiles:
      - streamlit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  shared-workspace:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: . # Current directory

networks:
  scraper-network:
    driver: bridge
  spark-net:
    driver: bridge