services:
  web-scraper:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - neo4j-db

  neo4j-db:
    image: neo4j:4.4-community
    volumes:
      - /$HOME/neo4j/logs:/logs
      - /$HOME/neo4j/config:/config
      - /$HOME/neo4j/data:/data
      - /$HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
